sudo: required

language: php

php: 7.4

addons:
    apt:
        packages:
            - graphviz
            - rabbitmq-server

services:
    - rabbitmq

before_script:
    - phpenv config-rm xdebug.ini
    - composer install

script:
    - make test
