image: php:7.1

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - make configure-pipelines
          - make update-test
          - make test
        services:
          - rabbitmq

definitions:
  services:
    rabbitmq:
      image: rabbitmq:3
