imports:
    - { resource: private_services.yml }

services:
    imatic_notification.connection:
        class: Imatic\Notification\Driver\Amqp\Connection
        arguments:
            - @imatic_notification.connection_params
            - @imatic_notification.channel_factory
